### PR TITLE
Fixed for new update

### PR DESCRIPTION
**Pull request by Nekromateion**

### CODE REVIEW

**Comment by werewolf26** [comment]
keep getting error 
```log [22:06:42.651] [ERROR] Exception in Harmony patch of method VRCPlayer.Method_Private_Void_GameObject_VRC_AvatarDescriptor_Boolean_PDM_1(UnityEngine.GameObject, VRC.SDKBase.VRC_AvatarDescriptor, System.Boolean):
System.MissingMethodException: VRC.Player VRCPlayer.get_field_Private_Player_0()

  at (wrapper dynamic-method) VRCPlayer.Method_Private_Void_GameObject_VRC_AvatarDescriptor_Boolean_PDM_1_Patch1(VRCPlayer,UnityEngine.GameObject,VRC.SDKBase.VRC_AvatarDescriptor,bool)

  at (wrapper dynamic-method) VRCPlayer.Method_Private_Void_GameObject_VRC_AvatarDescriptor_Boolean_PDM_1_Patch1_il2cpp(intptr,intptr,intptr,bool)
```

**Comment by werewolf26** [comment]
Need to change ``private static bool ApiAvatarDownloadPatch(ApiAvatar __0)`` to ApiAvatarLoadPatch

**Comment by KeafyIsHere** [comment]
> Need to change `private static bool ApiAvatarDownloadPatch(ApiAvatar __0)` to ApiAvatarLoadPatch

this is before load

**Comment by KeafyIsHere** [comment]
> Need to change `private static bool ApiAvatarDownloadPatch(ApiAvatar __0)` to ApiAvatarLoadPatch

lol I see what you mean now 😂

**Comment by Nekromateion** [comment]
Oh lmao my bad was copying over stuff from the version I personally use xD
@KeafyIsHere @werewolf26

**Pull request merged**
